# Generated by Django 5.1.6 on 2025-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_slot_max_tfms_slot_presentation_day'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='slots',
            field=models.ManyToManyField(related_name='tracks', to='slots.slot'),
        ),
    ]
