# Generated by Django 5.2.1 on 2025-06-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='semesters.semester'),
        ),
    ]
