# Generated by Django 5.1.6 on 2025-04-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='slots',
        ),
    ]
