# Generated by Django 5.2.1 on 2025-05-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplication',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='institutions.institution'),
        ),
    ]
