# Generated by Django 5.1.6 on 2025-05-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_teacherapplication_additional_info_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherapplication',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='teacherapplication',
            name='certificate',
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='institutions.institution'),
        ),
    ]
