# Generated by Django 5.1.6 on 2025-05-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_teacherapplication_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
