version: '3.7'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 minio minio123;
      /usr/bin/mc rm -r --force local/media || true;
      /usr/bin/mc mb local/media;
      /usr/bin/mc anonymous set download local/media;
      "
volumes:
  minio-data:
