# Generated by Django 5.1.6 on 2025-05-02 20:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tfm_duration', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('max_tfms', models.PositiveIntegerField(default=2)),
                ('room', models.CharField(max_length=100)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='tracks.track')),
            ],
        ),
    ]
