# Generated by Django 5.1.6 on 2025-04-07 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tfms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tfm_duration', models.DurationField(default=datetime.timedelta(seconds=2700))),
                ('tfms', models.ManyToManyField(blank=True, to='tfms.tfm')),
            ],
        ),
    ]
