# Generated by Django 5.1.6 on 2025-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='room',
            field=models.CharField(default='Room A101', max_length=100),
            preserve_default=False,
        ),
    ]
