# Generated by Django 5.2.1 on 2025-05-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='track',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='tracks.track'),
            preserve_default=False,
        ),
    ]
