# Generated by Django 5.1.6 on 2025-05-19 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='tfm_duration',
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date(2025, 6, 16)),
            preserve_default=False,
        ),
    ]
