# Generated by Django 5.2.1 on 2025-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_alter_slot_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='pre_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
