# Generated by Django 5.1.6 on 2025-04-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_init_presentation_day'),
        ('slots', '0002_slot_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='max_tfms',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='slot',
            name='presentation_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.presentationday'),
        ),
    ]
