# Generated by Django 5.1.6 on 2025-04-17 17:04

import config.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_init_presentation_day'),
        ('slots', '0003_slot_max_tfms_slot_presentation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='presentation_day',
            field=models.ForeignKey(default=config.models.PresentationDay.get_or_create_singleton, on_delete=django.db.models.deletion.CASCADE, to='config.presentationday'),
        ),
    ]
