# Generated by Django 5.1.6 on 2025-04-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_alter_slot_presentation_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='tfms',
        ),
    ]
