# Generated by Django 5.1.6 on 2025-04-22 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_remove_slot_tfms'),
        ('tracks', '0003_remove_track_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='tracks.track'),
        ),
    ]
