# Generated by Django 5.1.6 on 2025-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('presentation_day', models.DateField()),
                ('min_judges', models.PositiveIntegerField(default=3)),
                ('max_judges', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
