# Generated by Django 5.1.6 on 2025-05-19 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='presentation_day',
            new_name='int_presentation_date',
        ),
        migrations.AddField(
            model_name='semester',
            name='daily_end_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='semester',
            name='daily_start_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='semester',
            name='last_presentation_date',
            field=models.DateField(default=datetime.date(2025, 5, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='pre_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=2700)),
        ),
    ]
