# Generated by Django 5.1.6 on 2025-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='max_judges',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='semester',
            name='min_judges',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
