# Generated by Django 5.1.6 on 2025-05-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_rename_presentation_day_semester_int_presentation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='max_judges',
            new_name='max_committees',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='min_judges',
            new_name='min_committees',
        ),
    ]
