# Generated by Django 5.1.6 on 2025-05-16 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribunals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'President'), ('secretary', 'Secretary'), ('vocal', 'Vocal')], max_length=20)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='tribunals.tribunal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tribunal', 'user')},
            },
        ),
    ]
