# Generated by Django 5.1.6 on 2025-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'President'), ('secretary', 'Secretary'), ('vocal', 'Vocal')], max_length=20)),
            ],
        ),
    ]
