# Generated by Django 5.1.6 on 2025-05-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_initial'),
        ('tribunals', '0002_remove_tribunal_judges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='tribunals.tribunal'),
        ),
    ]
