# Generated by Django 5.2.1 on 2025-05-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        ('tribunals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='tribunals.tribunal'),
        ),
    ]
