# Generated by Django 5.1.6 on 2025-04-07 16:43

from django.db import migrations

def create_presentation_day(apps, schema_editor):
    PresentationDay = apps.get_model('config', 'PresentationDay')
    if not PresentationDay.objects.exists():
        PresentationDay.objects.create(date="2025-06-15")  # 👈 Set your default date here

class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_presentation_day),
    ]
