# Generated by Django 5.1.6 on 2025-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfm',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tfms/attachments/'),
        ),
    ]
