# Generated by Django 5.1.6 on 2025-04-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfm',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
