# Generated by Django 5.2.1 on 2025-05-19 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tfms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tfm',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tfms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tfm',
            name='directors',
            field=models.ManyToManyField(related_name='directed_tfms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tfmreview',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tfmreview',
            name='tfm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tfms.tfm'),
        ),
    ]
