name: CI - Django Tests with MinIO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

      minio:
        image: bitnami/minio:latest
        ports:
          - "9000:9000"
          - "9001:9001"
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: minio123

    env:
      DEBUG: true
      SECRET_KEY: django-insecure-J8VliX3EyI4hak5LuS6YW9bojYdIkKT1UvVHt3sQ-FkvyUJHTtw_9S7EHXlW3nAtAvw
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_STORAGE_BUCKET_NAME: media
      AWS_S3_ENDPOINT_URL: http://localhost:9000
      MINIO_ACCESS_URL: http://localhost:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Wait for MinIO to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:9000/minio/health/ready; then
              echo "MinIO is ready"
              break
            fi
            echo "Waiting for MinIO to be ready..."
            sleep 4
          done

      - name: Init MinIO bucket
        run: |
          curl -o mc https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set local http://localhost:9000 minio minio123
          ./mc mb local/media || true
          ./mc policy set public local/media

      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
