# Generated by Django 5.1.6 on 2025-05-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judges', '0001_initial'),
        ('slots', '0001_initial'),
        ('tfms', '0002_alter_tfm_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('judges', models.ManyToManyField(related_name='tribunals', through='judges.Judge', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunals', to='slots.slot')),
                ('tfm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tfms.tfm')),
            ],
            options={
                'unique_together': {('slot', 'index')},
            },
        ),
    ]
