# Generated by Django 5.1.6 on 2025-05-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slots', '0001_initial'),
        ('tfms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunals', to='slots.slot')),
                ('tfm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tfms.tfm')),
            ],
            options={
                'unique_together': {('slot', 'index')},
            },
        ),
    ]
