# Generated by Django 5.1.6 on 2025-04-17 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='president',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='tribunal',
            name='vocals',
        ),
        migrations.CreateModel(
            name='TribunalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'President'), ('secretary', 'Secretary'), ('vocal', 'Vocal')], max_length=20)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribunals.tribunal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tribunal', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tribunal',
            name='members',
            field=models.ManyToManyField(through='tribunals.TribunalMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
