# Generated by Django 5.1.6 on 2025-05-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='judges',
        ),
    ]
