# Generated by Django 5.2.1 on 2025-06-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_slot_pre_duration'),
        ('tfms', '0002_initial'),
        ('tribunals', '0002_tribunal_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tribunals', to='slots.slot'),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='tfm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tfms.tfm'),
        ),
    ]
