# Generated by Django 5.1.6 on 2025-04-17 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0002_remove_tribunal_president_remove_tribunal_secretary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='members',
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', 'President'), ('secretary', 'Secretary'), ('vocal', 'Vocal')], max_length=20)),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_entries', to='tribunals.tribunal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tribunal', 'user')},
            },
        ),
        migrations.AddField(
            model_name='tribunal',
            name='judges',
            field=models.ManyToManyField(related_name='tribunals', through='tribunals.Judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TribunalMember',
        ),
    ]
