# Generated by Django 5.2.1 on 2025-06-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfms', '0002_initial'),
        ('tribunals', '0003_tribunal_confirmed_alter_tribunal_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='tfm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tfms.tfm'),
        ),
    ]
