# Generated by Django 5.1.6 on 2025-04-17 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
        ('tribunals', '0003_remove_tribunal_members_judge_tribunal_judges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='judges',
            field=models.ManyToManyField(related_name='tribunals', through='judges.Judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
