# Generated by Django 5.1.6 on 2025-04-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_alter_slot_presentation_day'),
        ('tribunals', '0004_alter_tribunal_judges_delete_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunals', to='slots.slot'),
        ),
    ]
