# Generated by Django 5.1.6 on 2025-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunals', '0005_alter_tribunal_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribunal',
            name='index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
