# Generated by Django 5.1.6 on 2025-04-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_slot_track'),
        ('tribunals', '0006_tribunal_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tribunal',
            unique_together={('slot', 'index')},
        ),
    ]
